aaa/urls.py
from django.urls import path
from . import views

urlpatterns= [    
    path('', views.articles, name="articles"),
    path('index/', views.index, name="index"),
    path('throw/', views.data_throw, name="data-throw"),
    path('catch/', views.data_catch, name="data-catch"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.article_detail, name="article_detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/update/', views.update, name="update"),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("loout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password")
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from aaa import views
from django.conf import settings
from django.conf.urls.static import static

from aaa import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('aaa/', include("aaa.urls")),
    path('users/', include('users.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path("", views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

aaa/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image =models.ImageField(upload_to="images/", blank=True)

    def __str__(self):
        return self.title

accounts/models.py
from django.db import models

# Create your models here.

aaa/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ('created_at', 'updated_at')

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.urls import reverse

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "email",
        ]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            if self.fields.get("password"):
                password_help_text = (
                    "You can change the password " '<a href="{}">here</a>.'
                ).format(f"{reverse('accounts:change_password')}")
                self.fields["password"].help_text = password_help_text

aaa/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

# Create your views here.
def index(request):
    return render(request, "index.html")

def articles(request):
    articles = Article.objects.all().order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "articles.html", context)

def article_detail(request,pk):
    article = Article.objects.get(pk=pk)
    context = {"article": article,}
    return render(request, "article_detail.html", context)

def data_throw(request):
    return render(request, "data_throw.html")

def data_catch(request):
    data = request.GET.get("message")
    context = {
        "data": data,
            }

    return render(request, "data_catch.html", context)

@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES) #데이터 바인딩된 폼
        if form.is_valid():
        #데이터를 저장
            article = form.save() 
        # 다른곳으로 리다이렉트
            return redirect("article_detail", article.pk)
    else:
            form = ArticleForm()
    context = {"form": form}    
    return render(request, "create.html", context)
    

def delete(request, pk):
    if request.method == "POST":
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect("articles")
    return redirect("article_detail", pk)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect("article_detail", article.pk)
    else:
        form = ArticleForm(instance=article)

    context = {
        "form" : form,
        "article": article,
    }
    return render(request, "update.html", context)
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm)
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST
from django.views.decorators.http import require_http_methods
from .forms import CustomUserChangeForm


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get("next") or "index"
            return redirect(next_url)


    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)

@require_POST
def logout(request):
        if request.user.is_authenticated:
            auth_logout(request)
        return redirect("index")

@require_http_methods({"GET", "POST"})
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("index")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect("index")

@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)

@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

def users(request):
    return render(request, "users.html")

def profile(request, username):
    context = {
        "username": username,
    }
    return render(request, "profile.html", context)

aaa/templates/article_detail.html
{% extends "base.html" %}

{% block content %}
<h2>Article Detail</h2>

    <h3>제목:{{ article.title }}</h3>
	{% if article.image %}
		<img src="{{ article.image.url }}">
    {% endif %}	

    <p>게시글: {{ article.content }}</p>
    <p>작성 시간: {{ article.created_at }}</p>
    <p>수정일시 :</p>{{ article.updated_at }}</p>

    <a href="{% url 'articles' %}">목록 보기
        
    </a>
    <a href="{% url 'update' article.pk %}">
        <button>수정하기</button>
    </a>

    <form action="{% url 'delete' article.pk %}" method="post">
        {% csrf_token%}
        <input type="submit" value="삭제">
    </form>

{% endblock content %}

aaa/templates/articles.html
{% extends 'base.html' %}

{% block content %}
<h1>안녕 클레오파트라 세상에서 제일 가는 포테이토칩</h1>

{% if request.user.is_authenticated %}
    <a href="{% url 'create' %}">
    
    <button>새로운 글 작성</button>
    </a>

{% else %}
    <a href="{% url 'accounts:login' %}">로그인하고 글 작성하기</a>
{% endif %}

{% for article in articles %}
    <a href="{% url 'article_detail' article.pk %}">
        <p>[ {{ article.pk }} ] {{ article.title }}</p>
    </a>




    {% endfor %}

{% endblock content %}

aaa/templates/create.html
{% extends 'base.html' %}

{% block content %}
<h1> New Aaa</h1>

<form action="{% url 'create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    {{ form.as_p}}

    <button type="submit">저장</button>

</form>

<a href="{% url 'articles' %}">목록으로</a>

{% endblock content %}

aaa/templates/data_catch.html
{% extends 'base.html' %}

{% block content %}
    <h1> Data Catch</h1>

    <h3> Current Data</h2>
    <p>Current data is: {{ message }}</p>

    <a href="{% url 'data-throw' %}"> 입력 하러 가기!</a>


</form>
{% endblock content %}

aaa/templates/data_throw.html
{% extends 'base.html' %}

{% block content %}
    <h1>Data Throw</h1>

    <form action="{% url 'data-catch' %}" method="GET">

        <label for="my-data">데이터 입력  </label>
        <input type="text" id="message" name="message">

        <button type="submit">확인</button>


    </form>
    <a href="{% url 'index' %}"> 홈으로 가기</a>
{% endblock content %}

aaa/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h1> Edit</h1>

<form action="{% url 'update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">제목</label>
    <input type="text" name="title" id="title" value="{{ article.title }}">
    <br><br>

    <label for="">내용</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br><br>

    <button type="submit">수정</button>

</form>

<a href="{% url 'article_detail' article.pk %}">이전으로</a>

{% endblock content %}

aaa/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content%}
<h1>안녕?, 우영!</h1>

    <img src="{% static 'aaa/dasdas.jpg' %}"><br>

    
    <a href="{% url 'data-throw' %}">Throw로 이동</a><br>
    <a href="{% url 'users' %}">users로 이동</a><br>
    <a href="{% url 'articles' %}">목록으로</a><br>
    {% endblock content%}

aaa/templates/new.html
{% extends 'base.html' %}

{% block content %}
<h1> New Aaa</h1>

<form action="{% url 'create' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목</label>
    <input type="text" name="title">
    <br><br>

    <label for="">내용</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br><br>

    <button type="submit">저장</button>

</form>

<a href="{% url 'articles' %}">목록으로</a>

{% endblock content %}

aaa/templates/update.html
{% extends 'base.html' %}

{% block content %}
<h1> Edit</h1>

<form action="{% url 'update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>

</form>

<a href="{% url 'article_detail' article.pk %}">이전으로</a>

{% endblock content %}

aaa/templates/users.html
{% extends 'base.html' %}

{% block content%}
<h1>아주 쉽구요</h1>
{% endblock content %}

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">로그인</button>
</form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">회원가입</button>


</form>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
    <h1>회원정보수정</h1>
    
    <form action="{% url 'accounts:update' %}" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">수정하기</button>
    </form>

{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>

    {% block head %}{% endblock head %}
</head>
<body>

    <div class="navbar">


        {% if request.user.is_authenticated %}
        <h1>안녕 바바는 너야, {{ request.user.username }}</h1>

        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃"></input>
        </form>
        <a href="{% url 'accounts:update' %}">회원정보수정</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴">
        </form>

        {% else %}


        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        

        {% endif %}




    
    
    
    </div>
    

    <div class="container">
        {% block content%}
        {% endblock content %}
    </div>
    
</body>
</html>

users/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1> {{ username }} 프로필 페이지</h1>
    <h2> username : {{ username }}</h2>

    <a href="/index/"> 홈으로 돌아가기</a>
{% endblock content %}

users/templates/users.html
{% extends 'base.html' %}

{% block content%}
<h1>아주 쉽구요</h1>
<a href="{% url 'index' %}">홈으로 가기</a>
{% endblock content %}